class AsciiMap < Formula
  include Language::Python::Virtualenv

  desc "Terminal-based ASCII map explorer"
  homepage "https://github.com/Luthiraa/ascii-map"
  url "https://github.com/Luthiraa/ascii-map/archive/v0.1.0.tar.gz"
  sha256 "8a0b010f02e36aec1ef5a98220ce82ff35c131b637bda553e337d29f43824320"
  license "MIT"

  depends_on "python@3.11"
  # Add other system dependencies if needed
  # depends_on "protobuf"

  # Resources generated by custom script
  resource "certifi" do
    url "https://files.pythonhosted.org/packages/e0/2d/a891ca51311197f6ad14a7ef42e2399f36cf2f9bd44752b3dc4eab60fdc5/certifi-2025.1.31.tar.gz"
    sha256 "3ebdeeb36d274070a9b0c2a71d798d1a1158674514ba2a58d3480072d627376a"
  end

  resource "charset-normalizer" do
    url "https://files.pythonhosted.org/packages/13/69/33ddede1939fdd074bce5434295f38fae7136463422fe4fd3e0e89b98062/charset_normalizer-3.4.1.tar.gz"
    sha256 "4192663eb4c75ca7732a3fc2667d8f583af41a2791653fea556a31c19b085731"
  end

  resource "idna" do
    url "https://files.pythonhosted.org/packages/6f/6d/0703ccc57f3a7233505399edb88de3cbd678da106337b9fcde432b65ed60/idna-3.10.tar.gz"
    sha256 "12f65c9b470ab0b375b6fa11e5a740361675a894793d56f5c8e44208ed6b23d9"
  end

  resource "requests" do
    url "https://files.pythonhosted.org/packages/c9/74/b3ff8e6c8446842c3f5c837e9c3dfcfe2018ea6ecef224c710c85ef728f4/requests-2.32.3.tar.gz"
    sha256 "553654177d4eb1e28518cf036ec37e02e1b4b57ccafc206e9ec19b31d368e0d4"
  end

  resource "urllib3" do
    url "https://files.pythonhosted.org/packages/c7/24/5f1b3bdffd70275f6661c76461e25f024d5a38a46f04aaca912426a2b1d3/urllib3-2.3.0.tar.gz"
    sha256 "1d0db2d0f04df344f664a4bf855e9b986b2451f28681432f819074fd441d8df5"
  end

  resource "numpy" do
    url "https://files.pythonhosted.org/packages/57/fd/0005efbd0af48e55eb3c7208af93f2862d4b1a56cd78e84309a2d959208d/numpy-2.2.3.tar.gz"
    sha256 "dbdc1e67d264f3310b1d3d93708e13ba97bf97d34190b9f931666994762c2f7b"
  end

  resource "mapbox-vector-tile" do
    url "https://files.pythonhosted.org/packages/08/96/95d85d7742d8d8c3614138676d9cc7d6ac47df83c4add68962f831b4028c/mapbox-vector-tile-2.2.0.tar.gz"
    sha256 "a464523c99a80e4f3a9e2101df499f54bd443f0724620f4c0228d7a17dd1f66d"
  end

  resource "protobuf" do
    url "https://files.pythonhosted.org/packages/cd/c6/327732d8478440c9464560ea513b6329ced6b0058e5cb1628d689617ac2f/protobuf-5.29.3.tar.gz"
    sha256 "944a3311394c0388277274bd183f3ee33f789fc55416b063162cc71fbafed58a"
  end

  resource "pyclipper" do
    url "https://files.pythonhosted.org/packages/60/a4/ae7e3240e513a8936dd3de6143c6838df2946c5921869e9882250269f8c0/pyclipper-1.3.0.post6.tar.gz"
    sha256 "ee648eaf7e8a937a3f59e09d5dd29c42502d33457a4128f7fcb1d402b8006e8b"
  end

  resource "shapely" do
    url "https://files.pythonhosted.org/packages/08/6c/40a02d41b590e0c0362c3f8f12c299e52c92e105e6b77ae587b1c3413994/shapely-2.0.7.tar.gz"
    sha256 "22b5e28a994791ea822ef2e55734280f2d48074d22b274c5d5d8525b683e9b11"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    system "#{bin}/ascii-map", "--help"
  end
end
