class AsciiMap < Formula
  include Language::Python::Virtualenv

  desc "Terminal-based ASCII map explorer"
  homepage "https://github.com/Luthiraa/ascii-map"
  url "https://github.com/Luthiraa/ascii-map/archive/v0.1.0.tar.gz"
  sha256 "8a0b010f02e36aec1ef5a98220ce82ff35c131b637bda553e337d29f43824320"
  license "MIT"

  depends_on "python@3.11"
  # Add other system dependencies if needed
  # depends_on "protobuf"

    # Resources generated by poet
    resource "certifi" do
      url "https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40bab01fbf20a44/certifi-2024.7.4.tar.gz"
      sha256 "c198e21b1289c2ab85ee4e67bb4b4ef3ead0892059901a8d5b622f24a1101e90"
    end

    resource "charset-normalizer" do
      url "https://files.pythonhosted.org/packages/63/09/c60999676c38b7d916aa9553632989c67a365e53b92040aa415ebc2986f1/charset_normalizer-3.3.2.tar.gz"
      sha256 "03a95078832a893cb523f46f491c305c4ce12ee7f828135832a87a2624479e0a"
    end

    resource "idna" do
      url "https://files.pythonhosted.org/packages/bf/3f/8846da7c7482813b5e408ad3b6e828108a8927827e87b7a421422789f2a2/idna-3.7.tar.gz"
      sha256 "028ff3aadf0609c1fd30eb88715600396a841751936618addc07e6b79788e8d1"
    end

    resource "requests" do
      url "https://files.pythonhosted.org/packages/64/59/a0972b260d777d13862cd86b627997972ba96ba07c089ad06ded02e96417/requests-2.32.3.tar.gz"
      sha256 "553654177d4eb1e28518cf036ec37e02e1b4b57ccafc206e9ec19b31d368e0d4"
    end

    resource "urllib3" do
      url "https://files.pythonhosted.org/packages/3d/8c/ecf325d70e4bb8427976e33f37b198a280628e8339dae0787e660e549176/urllib3-2.2.2.tar.gz"
      sha256 "dd505485549a7a552833da5e6063639d0d177c04f23bc3864e41e5dc5f612168"
    end

    resource "numpy" do
      url "https://files.pythonhosted.org/packages/f3/0e/418f75c2250280eb447470fcf1013401764673895e62c1613ac33f443588/numpy-2.0.1.tar.gz"
      sha256 "395642c262eb4632a76f2f3dcee741a3d344445582c0029b35e839213155792a"
    end

    resource "mapbox-vector-tile" do
      url "https://files.pythonhosted.org/packages/a7/ea/87ab0d7f1d532a26c45938392d244238e8270104ad546875743477813a30/mapbox-vector-tile-2.0.1.tar.gz"
      sha256 "c08977d287040409747970868f029019688b13936999335552382906b3286311"
    end

    resource "protobuf" do
      url "https://files.pythonhosted.org/packages/15/8e/349479361622383842cb362f689e490516641b4e2141505304918f602263/protobuf-5.27.2.tar.gz"
      sha256 "94d18080648c089be67d3ea2d51199a5180f1ce2b040d6cd101c504ca4334346"
    end

    resource "pyclipper" do
      url "https://files.pythonhosted.org/packages/0c/33/c4e723555b79654117075253896593452f13264426557876a2679412f177/pyclipper-1.3.0.post5.tar.gz"
      sha256 "ca52ec2476b7ae48df1f7bd8ce74f9d0c266f5db1d80b6a695a43152d1264c18"
    end

    resource "shapely" do
      url "https://files.pythonhosted.org/packages/3f/8a/8bd16501c238b9399881882bd54519f64bfad3d201c107f9c21f7c70f06f/shapely-2.0.5.tar.gz"
      sha256 "dc937eb7f6312521c8340d862973842c1619a96e5eb604618778f24b2164a66a"
    end

    # Link the executable
    bin.install_symlink libexec/"bin/ascii-map"
  end

  test do
    system "#{bin}/ascii-map", "--help"
  end
end
